using System.Text.Json;
using Minicloud.Cli.Config;

namespace Minicloud.Cli.Commands;

internal static class DockerfileGenerator
{
    public static bool TryWriteDockerfile(MinicloudServiceConfig service, out string dockerfilePath, out string? reason)
    {
        dockerfilePath = EffectiveDockerfilePath(service);
        reason = null;

        if (File.Exists(dockerfilePath))
        {
            return true;
        }

        if (string.IsNullOrWhiteSpace(service.SourcePath) || !Directory.Exists(service.SourcePath))
        {
            reason = "service source path does not exist";
            return false;
        }

        var dockerfile = TryCreateDockerfile(service.SourcePath, service.Port ?? 8080, out reason);
        if (dockerfile is null)
        {
            return false;
        }

        var directory = Path.GetDirectoryName(dockerfilePath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(dockerfilePath, dockerfile);
        return true;
    }

    internal static string? TryCreateDockerfile(string sourcePath, int port, out string? reason)
    {
        reason = null;

        var packageJsonPath = Path.Combine(sourcePath, "package.json");
        if (File.Exists(packageJsonPath))
        {
            return CreateNodeDockerfile(packageJsonPath, port, out reason);
        }

        var csproj = Directory.EnumerateFiles(sourcePath, "*.csproj", SearchOption.TopDirectoryOnly)
            .OrderBy(Path.GetFileName, StringComparer.Ordinal)
            .FirstOrDefault();
        if (csproj is not null)
        {
            return CreateDotNetDockerfile(csproj, port, out reason);
        }

        if (File.Exists(Path.Combine(sourcePath, "pom.xml")) ||
            File.Exists(Path.Combine(sourcePath, "build.gradle")) ||
            File.Exists(Path.Combine(sourcePath, "build.gradle.kts")))
        {
            return CreateSpringBootDockerfile(port);
        }

        reason = "unsupported project type";
        return null;
    }

    private static string? CreateNodeDockerfile(string packageJsonPath, int port, out string? reason)
    {
        var package = ReadPackageJson(packageJsonPath);
        reason = null;

        if (package.Dependencies.Contains("vite"))
        {
            return $$"""
                # Generated by minicloud deploy
                FROM node:22-alpine
                WORKDIR /app

                COPY package*.json ./
                RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

                COPY . .

                EXPOSE {{port}}
                CMD ["sh", "-c", "npm run build && npx vite preview --host 0.0.0.0 --port {{port}}"]
                """;
        }

        if (package.Dependencies.Contains("next"))
        {
            return $$"""
                # Generated by minicloud deploy
                FROM node:22-alpine
                WORKDIR /app

                COPY package*.json ./
                RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

                COPY . .

                EXPOSE {{port}}
                CMD ["sh", "-c", "npm run build && npx next start -H 0.0.0.0 -p {{port}}"]
                """;
        }

        if (package.Dependencies.Contains("express") ||
            package.Dependencies.Contains("fastify") ||
            package.Dependencies.Contains("@nestjs/core"))
        {
            return $$"""
                # Generated by minicloud deploy
                FROM node:22-alpine
                WORKDIR /app

                COPY package*.json ./
                RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

                COPY . .
                RUN npm run build --if-present

                EXPOSE {{port}}
                CMD ["npm", "run", "start"]
                """;
        }

        reason = "unsupported Node project type";
        return null;
    }

    private static string? CreateDotNetDockerfile(string csprojPath, int port, out string? reason)
    {
        var projectText = File.ReadAllText(csprojPath);
        if (!projectText.Contains("Microsoft.NET.Sdk.Web", StringComparison.OrdinalIgnoreCase))
        {
            reason = "unsupported .NET project type";
            return null;
        }

        reason = null;
        return $$"""
            # Generated by minicloud deploy
            FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
            WORKDIR /src
            COPY . .
            RUN dotnet publish -c Release -o /app/publish

            FROM mcr.microsoft.com/dotnet/aspnet:10.0
            WORKDIR /app
            COPY --from=build /app/publish .
            ENV ASPNETCORE_URLS=http://+:{{port}}
            EXPOSE {{port}}
            ENTRYPOINT ["sh", "-c", "dotnet *.dll"]
            """;
    }

    private static string CreateSpringBootDockerfile(int port) =>
        $$"""
            # Generated by minicloud deploy
            FROM eclipse-temurin:21-jdk-alpine AS build
            WORKDIR /src
            COPY . .
            RUN if [ -f ./mvnw ]; then ./mvnw -DskipTests package; elif [ -f ./gradlew ]; then ./gradlew bootJar -x test; elif [ -f pom.xml ]; then apk add --no-cache maven && mvn -DskipTests package; else apk add --no-cache gradle && gradle bootJar -x test; fi
            RUN jar_path="$(find target build/libs -maxdepth 1 -name '*.jar' ! -name '*plain.jar' 2>/dev/null | head -n 1)" && test -n "$jar_path" && mkdir -p /app/publish && cp "$jar_path" /app/publish/app.jar

            FROM eclipse-temurin:21-jre-alpine
            WORKDIR /app
            COPY --from=build /app/publish/app.jar /app/app.jar
            EXPOSE {{port}}
            ENTRYPOINT ["java", "-jar", "/app/app.jar"]
            """;

    private static PackageJsonInfo ReadPackageJson(string path)
    {
        try
        {
            using var document = JsonDocument.Parse(File.ReadAllText(path));
            var root = document.RootElement;
            var dependencies = new HashSet<string>(StringComparer.Ordinal);
            AddObjectKeys(root, "dependencies", dependencies);
            AddObjectKeys(root, "devDependencies", dependencies);
            return new PackageJsonInfo(dependencies);
        }
        catch (JsonException)
        {
            return new PackageJsonInfo(new HashSet<string>(StringComparer.Ordinal));
        }
    }

    private static void AddObjectKeys(JsonElement root, string propertyName, ISet<string> keys)
    {
        if (!root.TryGetProperty(propertyName, out var element) || element.ValueKind != JsonValueKind.Object)
        {
            return;
        }

        foreach (var property in element.EnumerateObject())
        {
            keys.Add(property.Name);
        }
    }

    private static string EffectiveDockerfilePath(MinicloudServiceConfig service) =>
        string.IsNullOrWhiteSpace(service.Dockerfile)
            ? Path.Combine(service.SourcePath!, "Dockerfile")
            : service.Dockerfile;

    private sealed record PackageJsonInfo(ISet<string> Dependencies);
}
