using System.Text.Json;
using Minicloud.Cli.Config;

namespace Minicloud.Cli.Commands;

internal static class DockerfileGenerator
{
    public static bool TryWriteDockerfile(MinicloudServiceConfig service, out string dockerfilePath, out string? reason)
    {
        dockerfilePath = EffectiveDockerfilePath(service);
        reason = null;

        if (File.Exists(dockerfilePath))
        {
            return true;
        }

        if (string.IsNullOrWhiteSpace(service.SourcePath) || !Directory.Exists(service.SourcePath))
        {
            reason = "service source path does not exist";
            return false;
        }

        var dockerfile = TryCreateDockerfile(service.SourcePath, service.Port ?? 8080, service.BuildEnv, out reason);
        if (dockerfile is null)
        {
            return false;
        }

        var directory = Path.GetDirectoryName(dockerfilePath);
        if (!string.IsNullOrWhiteSpace(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(dockerfilePath, dockerfile);
        return true;
    }

    internal static string? TryCreateDockerfile(
        string sourcePath,
        int port,
        IReadOnlyDictionary<string, string>? buildEnv,
        out string? reason)
    {
        reason = null;

        var packageJsonPath = Path.Combine(sourcePath, "package.json");
        if (File.Exists(packageJsonPath))
        {
            return CreateNodeDockerfile(packageJsonPath, port, buildEnv, out reason);
        }

        var csproj = Directory.EnumerateFiles(sourcePath, "*.csproj", SearchOption.TopDirectoryOnly)
            .OrderBy(Path.GetFileName, StringComparer.Ordinal)
            .FirstOrDefault();
        if (csproj is not null)
        {
            return CreateDotNetDockerfile(csproj, port, out reason);
        }

        if (File.Exists(Path.Combine(sourcePath, "pom.xml")) ||
            File.Exists(Path.Combine(sourcePath, "build.gradle")) ||
            File.Exists(Path.Combine(sourcePath, "build.gradle.kts")))
        {
            return CreateSpringBootDockerfile(sourcePath, port);
        }

        reason = "unsupported project type";
        return null;
    }

    private static string? CreateNodeDockerfile(
        string packageJsonPath,
        int port,
        IReadOnlyDictionary<string, string>? buildEnv,
        out string? reason)
    {
        var package = ReadPackageJson(packageJsonPath);
        reason = null;

        if (package.Dependencies.Contains("vite"))
        {
            var buildArguments = BuildArgumentDeclarations(buildEnv);
            return $$"""
                # Generated by minicloud deploy
                FROM node:22-alpine AS build
                WORKDIR /app

                COPY package*.json ./
                RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

                COPY . .
                {{buildArguments}}
                RUN npm run build

                FROM node:22-alpine
                WORKDIR /app
                RUN npm install --global serve@14
                COPY --from=build /app/dist ./dist
                EXPOSE {{port}}
                CMD ["serve", "-s", "dist", "-l", "{{port}}"]
                """;
        }

        if (package.Dependencies.Contains("next"))
        {
            var buildArguments = BuildArgumentDeclarations(buildEnv);
            return $$"""
                # Generated by minicloud deploy
                FROM node:22-alpine AS dependencies
                WORKDIR /app

                COPY package*.json ./
                RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

                FROM node:22-alpine AS build
                WORKDIR /app
                COPY --from=dependencies /app/node_modules ./node_modules
                COPY . .
                {{buildArguments}}
                RUN npm run build

                FROM node:22-alpine
                WORKDIR /app
                ENV NODE_ENV=production
                COPY --from=build /app/package*.json ./
                COPY --from=build /app/node_modules ./node_modules
                COPY --from=build /app/.next ./.next
                COPY --from=build /app/public ./public
                EXPOSE {{port}}
                CMD ["sh", "-c", "npx next start -H 0.0.0.0 -p {{port}}"]
                """;
        }

        if (package.Dependencies.Contains("express") ||
            package.Dependencies.Contains("fastify") ||
            package.Dependencies.Contains("@nestjs/core"))
        {
            return $$"""
                # Generated by minicloud deploy
                FROM node:22-alpine
                WORKDIR /app

                COPY package*.json ./
                RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

                COPY . .
                RUN npm run build --if-present

                EXPOSE {{port}}
                CMD ["npm", "run", "start"]
                """;
        }

        reason = "unsupported Node project type";
        return null;
    }

    private static string BuildArgumentDeclarations(IReadOnlyDictionary<string, string>? buildEnv) =>
        buildEnv is not { Count: > 0 }
            ? string.Empty
            : string.Join('\n', buildEnv.Keys.OrderBy(key => key, StringComparer.Ordinal).Select(key => $"ARG {key}"));

    private static string? CreateDotNetDockerfile(string csprojPath, int port, out string? reason)
    {
        var projectText = File.ReadAllText(csprojPath);
        if (!projectText.Contains("Microsoft.NET.Sdk.Web", StringComparison.OrdinalIgnoreCase))
        {
            reason = "unsupported .NET project type";
            return null;
        }

        reason = null;
        var projectFile = Path.GetFileName(csprojPath);
        return $$"""
            # Generated by minicloud deploy
            FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
            WORKDIR /src
            COPY {{projectFile}} ./
            RUN --mount=type=cache,target=/root/.nuget/packages,sharing=locked dotnet restore {{projectFile}}
            COPY . .
            RUN --mount=type=cache,target=/root/.nuget/packages,sharing=locked dotnet publish {{projectFile}} -c Release --no-restore -o /app/publish

            FROM mcr.microsoft.com/dotnet/aspnet:10.0
            WORKDIR /app
            COPY --from=build /app/publish .
            ENV ASPNETCORE_URLS=http://+:{{port}}
            EXPOSE {{port}}
            ENTRYPOINT ["sh", "-c", "dotnet *.dll"]
            """;
    }

    private static string CreateSpringBootDockerfile(string sourcePath, int port)
    {
        var isMaven = File.Exists(Path.Combine(sourcePath, "pom.xml"));
        var dependencyCopy = isMaven
            ? "COPY pom.xml ./" +
              (Directory.Exists(Path.Combine(sourcePath, ".mvn")) ? "\nCOPY .mvn ./.mvn" : string.Empty) +
              (File.Exists(Path.Combine(sourcePath, "mvnw")) ? "\nCOPY mvnw ./" : string.Empty)
            : "COPY build.gradle* settings.gradle* ./" +
              (File.Exists(Path.Combine(sourcePath, "gradlew")) ? "\nCOPY gradlew ./" : string.Empty) +
              (Directory.Exists(Path.Combine(sourcePath, "gradle")) ? "\nCOPY gradle ./gradle" : string.Empty);
        var dependencyCommand = isMaven
            ? "chmod +x ./mvnw 2>/dev/null || true; if [ -f ./mvnw ]; then ./mvnw -DskipTests dependency:go-offline; else apk add --no-cache maven && mvn -DskipTests dependency:go-offline; fi"
            : "chmod +x ./gradlew 2>/dev/null || true; if [ -f ./gradlew ]; then ./gradlew dependencies --no-daemon; else apk add --no-cache gradle && gradle dependencies --no-daemon; fi";
        var buildCommand = isMaven
            ? "if [ -f ./mvnw ]; then ./mvnw -DskipTests package; else mvn -DskipTests package; fi"
            : "if [ -f ./gradlew ]; then ./gradlew bootJar -x test --no-daemon; else gradle bootJar -x test --no-daemon; fi";
        return $$"""
            # Generated by minicloud deploy
            FROM eclipse-temurin:21-jdk-alpine AS build
            WORKDIR /src
            {{dependencyCopy}}
            RUN --mount=type=cache,target=/root/.m2,sharing=locked --mount=type=cache,target=/root/.gradle,sharing=locked {{dependencyCommand}}
            COPY . .
            RUN --mount=type=cache,target=/root/.m2,sharing=locked --mount=type=cache,target=/root/.gradle,sharing=locked {{buildCommand}}
            RUN jar_path="$(find target build/libs -maxdepth 1 -name '*.jar' ! -name '*plain.jar' 2>/dev/null | head -n 1)" && test -n "$jar_path" && mkdir -p /app/publish && cp "$jar_path" /app/publish/app.jar

            FROM eclipse-temurin:21-jre-alpine
            WORKDIR /app
            COPY --from=build /app/publish/app.jar /app/app.jar
            EXPOSE {{port}}
            ENTRYPOINT ["java", "-jar", "/app/app.jar"]
            """;
    }

    private static PackageJsonInfo ReadPackageJson(string path)
    {
        try
        {
            using var document = JsonDocument.Parse(File.ReadAllText(path));
            var root = document.RootElement;
            var dependencies = new HashSet<string>(StringComparer.Ordinal);
            AddObjectKeys(root, "dependencies", dependencies);
            AddObjectKeys(root, "devDependencies", dependencies);
            return new PackageJsonInfo(dependencies);
        }
        catch (JsonException)
        {
            return new PackageJsonInfo(new HashSet<string>(StringComparer.Ordinal));
        }
    }

    private static void AddObjectKeys(JsonElement root, string propertyName, ISet<string> keys)
    {
        if (!root.TryGetProperty(propertyName, out var element) || element.ValueKind != JsonValueKind.Object)
        {
            return;
        }

        foreach (var property in element.EnumerateObject())
        {
            keys.Add(property.Name);
        }
    }

    private static string EffectiveDockerfilePath(MinicloudServiceConfig service) =>
        string.IsNullOrWhiteSpace(service.Dockerfile)
            ? Path.Combine(service.SourcePath!, "Dockerfile")
            : service.Dockerfile;

    private sealed record PackageJsonInfo(ISet<string> Dependencies);
}
