using System.Text;
using System.Text.Json;
using YamlDotNet.RepresentationModel;

namespace Minicloud.Cli.Config;

public static class MinicloudConfigWriter
{
    public static string UpdateAppIdentity(string yaml, string app, string appId)
    {
        var stream = new YamlStream();
        stream.Load(new StringReader(yaml));
        var root = (YamlMappingNode)stream.Documents.Single().RootNode;
        var replacements = new List<(int Start, int Length, string Value)>();
        foreach (var (key, value) in root.Children)
        {
            var replacement = (key as YamlScalarNode)?.Value switch
            {
                "app" => app,
                "appId" => appId,
                _ => null
            };
            if (replacement is null || value is not YamlScalarNode scalar || scalar.Value == replacement)
            {
                continue;
            }

            replacements.Add(((int)value.Start.Index, (int)(value.End.Index - value.Start.Index), JsonSerializer.Serialize(replacement)));
        }

        foreach (var replacement in replacements.OrderByDescending(item => item.Start))
        {
            yaml = yaml.Remove(replacement.Start, replacement.Length).Insert(replacement.Start, replacement.Value);
        }

        return yaml;
    }

    public static string Write(MinicloudConfig config)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by minicloud init");
        builder.AppendLine($"app: {Escape(config.App)}");
        if (!string.IsNullOrWhiteSpace(config.AppId))
        {
            builder.AppendLine($"appId: {Escape(config.AppId)}");
        }

        if (!string.IsNullOrWhiteSpace(config.Database))
        {
            builder.AppendLine($"database: {Escape(config.Database)}");
        }

        if (!string.IsNullOrWhiteSpace(config.CommitSha))
        {
            builder.AppendLine($"commitSha: {Escape(config.CommitSha)}");
        }

        builder.AppendLine("services:");
        foreach (var (name, service) in config.Services)
        {
            builder.AppendLine($"  {Escape(name)}:");
            if (!string.IsNullOrWhiteSpace(service.SourcePath))
            {
                builder.AppendLine($"    sourcePath: {Escape(service.SourcePath)}");
            }

            if (!string.IsNullOrWhiteSpace(service.Dockerfile))
            {
                builder.AppendLine($"    dockerfile: {Escape(service.Dockerfile)}");
            }

            if (!string.IsNullOrWhiteSpace(service.Image))
            {
                builder.AppendLine($"    image: {Escape(service.Image)}");
            }

            builder.AppendLine($"    port: {service.Port}");
            builder.AppendLine($"    public: {service.Public?.ToString().ToLowerInvariant() ?? "true"}");
            builder.AppendLine($"    path: {Escape(service.Path ?? "/")}");
            builder.AppendLine($"    healthPath: {Escape(service.HealthPath ?? "/")}");
            if (service.Env is { Count: > 0 })
            {
                builder.AppendLine("    env:");
                foreach (var (key, value) in service.Env)
                {
                    builder.AppendLine($"      {Escape(key)}: {Escape(value)}");
                }
            }

            if (service.SecretEnv is { Count: > 0 })
            {
                builder.AppendLine("    secretEnv:");
                foreach (var (key, value) in service.SecretEnv)
                {
                    builder.AppendLine($"      {Escape(key)}: {Escape(value)}");
                }
            }

            if (service.BuildEnv is { Count: > 0 })
            {
                builder.AppendLine("    buildEnv:");
                foreach (var (key, value) in service.BuildEnv)
                {
                    builder.AppendLine($"      {Escape(key)}: {Escape(value)}");
                }
            }
        }

        return builder.ToString();
    }

    private static string Escape(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "\"\"";
        }

        return value.Any(character => char.IsWhiteSpace(character) || character is ':' or '#')
            ? $"\"{value.Replace("\"", "\\\"", StringComparison.Ordinal)}\""
            : value;
    }
}
