using System.Text;

namespace Municloud.Cli.Config;

public static class MunicloudConfigWriter
{
    public static string Write(MunicloudConfig config)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# Generated by municloud init");
        builder.AppendLine($"app: {Escape(config.App)}");
        if (!string.IsNullOrWhiteSpace(config.AppId))
        {
            builder.AppendLine($"appId: {Escape(config.AppId)}");
        }

        if (!string.IsNullOrWhiteSpace(config.Database))
        {
            builder.AppendLine($"database: {Escape(config.Database)}");
        }

        if (!string.IsNullOrWhiteSpace(config.CommitSha))
        {
            builder.AppendLine($"commitSha: {Escape(config.CommitSha)}");
        }

        builder.AppendLine("services:");
        foreach (var (name, service) in config.Services)
        {
            builder.AppendLine($"  {Escape(name)}:");
            if (!string.IsNullOrWhiteSpace(service.SourcePath))
            {
                builder.AppendLine($"    sourcePath: {Escape(service.SourcePath)}");
            }

            if (!string.IsNullOrWhiteSpace(service.Dockerfile))
            {
                builder.AppendLine($"    dockerfile: {Escape(service.Dockerfile)}");
            }

            if (!string.IsNullOrWhiteSpace(service.Image))
            {
                builder.AppendLine($"    image: {Escape(service.Image)}");
            }

            builder.AppendLine($"    port: {service.Port}");
            builder.AppendLine($"    public: {service.Public?.ToString().ToLowerInvariant() ?? "true"}");
            builder.AppendLine($"    path: {Escape(service.Path ?? "/")}");
            builder.AppendLine($"    healthPath: {Escape(service.HealthPath ?? "/")}");
            if (service.Env is { Count: > 0 })
            {
                builder.AppendLine("    env:");
                foreach (var (key, value) in service.Env)
                {
                    builder.AppendLine($"      {Escape(key)}: {Escape(value)}");
                }
            }
        }

        return builder.ToString();
    }

    private static string Escape(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "\"\"";
        }

        return value.Any(character => char.IsWhiteSpace(character) || character is ':' or '#')
            ? $"\"{value.Replace("\"", "\\\"", StringComparison.Ordinal)}\""
            : value;
    }
}
